on:
  pull_request:
    paths:
      - "dotnet/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install csharpier
        run: |
          dotnet tool install -g csharpier

      - name: Run csharpier
        run: |
          csharpier check dotnet
