# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "dotnet/servers/**"
#       - "typescript/servers/**"

# env:
#   DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
#   DOKPLOY_API_URL: ${{ vars.DOKPLOY_API_URL }}
#   DOKPLOY_GITHUB_URL: ${{ vars.DOKPLOY_GITHUB_URL }}
#   DOKPLOY_PROJECT_ID: ${{ vars.DOKPLOY_PROJECT_ID }}
#   DOKPLOY_SERVER_ID: ${{ vars.DOKPLOY_SERVER_ID }}
#   DOKPLOY_SUBDOMAIN: ${{ vars.DOKPLOY_SUBDOMAIN }}

# jobs:
#   deploy_mcp_servers:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Build pr-validator
#         working-directory: dotnet/pr-validator/DarenaHealth.Community.PrValidator
#         run: |
#           dotnet publish -c Release -r linux-x64

#       - name: Run deployer
#         working-directory: dotnet/pr-validator/DarenaHealth.Community.PrValidator/bin/Release/net8.0/linux-x64
#         run: |
#           CHANGED_FILES="$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | paste -sd ' ' -)";

#           echo "-- Verifying build & docker --";
#           ./pr-validator deploy-mcp-servers -c $CHANGED_FILES;
