name: Deploy to dev (typescript)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "typescript/**"

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-ts-env.yaml
    with:
      AZURE_WEBAPP_NAME: app-opensource-mcp-ts-po-dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
